import {useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronDown,ChevronRight,CircleHelp,Clock3,FileCheck2,FilePlus2,FileText,FolderOpen,GitBranch,Globe2,Layers3,Leaf,Link2,Loader2,Menu,MessageSquareText,Network,Pause,Play,Plus,RefreshCw,Search,ShieldCheck,Sparkles,Upload,Wallet,X,AlertTriangle,CheckCircle2,ExternalLink,Presentation,Settings2} from 'lucide-react';
import type {Budget,Claim,Evidence,ExportJob,Outline,Project,Report,ResearchEvent,Run,Source,Task} from './types';
import {api,post} from './api';
import {CollaborationImpact} from './CollaborationImpact';
import {activeRun,date,day,mergeEvents,money,quoteParts,safeSourceUrl,splitList,statusLabel} from './utils';

type Page='overview'|'sources'|'collaboration'|'report';
type Draft={title:string;question:string;audience:string;time_range:string;web_enabled:boolean;competitors:string;dimensions:string;mode:'synthetic'|'public'};
const initialDraft:Draft={title:'',question:'',audience:'管理层与产品团队',time_range:'最近12个月',web_enabled:true,competitors:'',dimensions:'目标客户，核心功能，价格与套餐，SSO，近期变化',mode:'public'};
const nav=[{id:'overview',label:'研究概览',icon:Layers3},{id:'sources',label:'资料与证据',icon:FolderOpen},{id:'collaboration',label:'协作进度',icon:Network},{id:'report',label:'报告与导出',icon:BookOpen}] as const;
const roleLabels:Record<string,string>={coordinator:'研究协调员',industry:'行业研究员',competitor:'竞品研究员',commercial:'商业分析员',verifier:'独立核查员',editor:'报告编辑员',researcher:'竞品研究员',verify:'独立核查员',report:'报告编辑员',planner:'研究协调员',analyst:'商业分析员',business:'商业分析员'};

function Button({children,className='',variant='secondary',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button className={`button ${variant} ${className}`} {...props}>{children}</button>}
function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Modal({title,description,children,onClose,wide=false,error}:{title:string;description?:string;children:ReactNode;onClose:()=>void;wide?:boolean;error?:string}){const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('input,textarea,select,button')?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')closeRef.current();if(event.key==='Tab'){const focusable=ref.current?.querySelectorAll<HTMLElement>('button,input,textarea,select,a[href],[tabindex="0"]');if(!focusable?.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);previous?.focus();};},[]);return <div className="modal-shade" onClick={onClose}><div ref={ref} tabIndex={-1} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div><button className="icon-button" aria-label="关闭弹窗" onClick={onClose}><X size={20}/></button></div>{error&&<div className="error-banner" role="alert"><AlertTriangle size={16}/><span>{error}</span></div>}{children}</div></div>}
function Empty({icon:Icon=BookOpen,title,body,children}:{icon?:typeof BookOpen;title:string;body:string;children?:ReactNode}){return <div className="empty-state"><span className="empty-icon"><Icon size={27}/></span><h3>{title}</h3><p>{body}</p>{children}</div>}
function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[project,setProject]=useState<Project|null>(null);
 const [page,setPage]=useState<Page>('overview'),[sources,setSources]=useState<Source[]>([]),[reports,setReports]=useState<Report[]>([]),[reportId,setReportId]=useState(''),[runs,setRuns]=useState<Run[]>([]),[runId,setRunId]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[events,setEvents]=useState<ResearchEvent[]>([]);
 const [budget,setBudget]=useState<Budget|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[sidebarOpen,setSidebarOpen]=useState(false);
 const [modal,setModal]=useState<'create'|'brief'|'outline'|'addSource'|'replace'|'revise'|'url'|null>(null),[draft,setDraft]=useState<Draft>(initialDraft),[outline,setOutline]=useState<Outline|null>(null);
 const [mode,setMode]=useState<'replay'|'live'>('replay'),[modelProfile,setModelProfile]=useState<'qwen-default'|'gemini-budget'>('gemini-budget'),[architecture,setArchitecture]=useState<'multi'|'single'|'pipeline'>('multi'),[runBudget,setRunBudget]=useState('0.15'),[advanced,setAdvanced]=useState(false);
 const [sourceDraft,setSourceDraft]=useState({title:'',text:'',competitor:'',kind:'document',published_at:'',url:''}),[replacing,setReplacing]=useState<Source|null>(null),[sourceFilter,setSourceFilter]=useState(''),[sourceQuery,setSourceQuery]=useState(''),[sourceHistory,setSourceHistory]=useState<Source[]>([]);
 const [inspect,setInspect]=useState<{source?:Source;quote?:string;claims?:Claim[]}|null>(null),[revision,setRevision]=useState(''),[exportJobs,setExportJobs]=useState<ExportJob[]>([]);
 const uploadRef=useRef<HTMLInputElement>(null),projectRef=useRef('');projectRef.current=projectId;
 const run=runs.find(r=>r.id===runId)??runs[0],report=reports.find(r=>r.id===reportId)??reports[0];
 const active=runs.some(r=>activeRun(r.status));
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),4500)};
 const perform=async(name:string,operation:()=>Promise<void>)=>{setBusy(name);setError('');try{await operation()}catch(e){setError(e instanceof Error?e.message:'操作失败，请重试')}finally{setBusy('')}};
 const loadProjects=useCallback(async()=>{const [list,summary]=await Promise.all([api<Project[]>('/projects'),api<Budget>('/budget')]);setProjects(list);setBudget(summary);return list},[]);
 const refresh=useCallback(async(id:string)=>{
   const [p,s,r,rs]=await Promise.all([api<Project>(`/projects/${id}`),api<Source[]>(`/projects/${id}/sources`),api<Report[]>(`/projects/${id}/reports`),api<Run[]>(`/projects/${id}/runs`)]);
   if(projectRef.current!==id)return;
   setProject(p);setSources(s);setReports(r.sort((a,b)=>b.version-a.version));setRuns(rs.sort((a,b)=>b.created_at.localeCompare(a.created_at)));setProjects(old=>old.map(item=>item.id===id?p:item));
 },[]);
 useEffect(()=>{let cancelled=false;loadProjects().then(list=>{if(cancelled)return;const stored=localStorage.getItem('briefforge.project');const selected=list.find(p=>p.id===stored)??list[0];if(selected){setProjectId(selected.id);setPage(selected.latest_report_id?'report':'overview')}}).catch(e=>setError(e.message)).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[loadProjects]);
 useEffect(()=>{if(!projectId)return;localStorage.setItem('briefforge.project',projectId);setLoading(true);setProject(null);setSources([]);setRuns([]);setReports([]);setRunId('');setReportId('');setTasks([]);setEvents([]);setInspect(null);refresh(projectId).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[projectId,refresh]);
 useEffect(()=>{if(!run)return;let stopped=false;setTasks([]);setEvents([]);const id=run.id;
   Promise.all([api<Task[]>(`/runs/${id}/tasks`),api<ResearchEvent[]>(`/runs/${id}/event-log`)]).then(([ts,es])=>{if(!stopped){setTasks(ts);setEvents(es)}}).catch(e=>!stopped&&setError(e.message));return()=>{stopped=true}
 },[run?.id]);
 useEffect(()=>{
   if(!run||!activeRun(run.status))return;
   const id=run.id,pid=run.project_id;let stopped=false,lastId=0,polling=false;
   const stream=new EventSource(`/api/runs/${id}/events`);
   stream.onmessage=(message)=>{try{const event:ResearchEvent=JSON.parse(message.data);lastId=Math.max(lastId,event.id);if(!stopped)setEvents(old=>mergeEvents(old,[event]))}catch{/* Ignore heartbeat frames. */}};
   const poll=async()=>{if(stopped||polling)return;polling=true;try{
     const [current,ts,es]=await Promise.all([api<Run>(`/runs/${id}`),api<Task[]>(`/runs/${id}/tasks`),api<ResearchEvent[]>(`/runs/${id}/event-log?after=${lastId}`)]);
     if(stopped)return;setTasks(ts);setEvents(old=>mergeEvents(old,es));es.forEach(event=>lastId=Math.max(lastId,event.id));setRuns(old=>old.map(item=>item.id===id?current:item));
     if(!activeRun(current.status)){await refresh(pid);await loadProjects();if(current.report_id){setReportId(current.report_id);setPage('report')}if(current.error)setError(current.error)}
   }catch(e){if(!stopped)setError(e instanceof Error?e.message:'连接中断，正在尝试恢复')}finally{polling=false}};
   const timer=window.setInterval(poll,2200);void poll();return()=>{stopped=true;stream.close();window.clearInterval(timer)};
 },[run?.id,run?.status,refresh,loadProjects]);
 useEffect(()=>{const pending=exportJobs.filter(j=>!['completed','failed'].includes(j.status));if(!pending.length)return;const timer=window.setInterval(()=>{void Promise.all(pending.map(j=>api<ExportJob>(`/exports/${j.id}`))).then(jobs=>setExportJobs(old=>old.map(j=>jobs.find(updated=>updated.id===j.id)??j))).catch(e=>setError(e.message))},1800);return()=>window.clearInterval(timer)},[exportJobs]);

 useEffect(()=>{if(!inspect)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setInspect(null)};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[!!inspect]);
 useEffect(()=>{const source=inspect?.source;setSourceHistory([]);if(!source)return;let cancelled=false;api<Source[]>(`/projects/${source.project_id}/sources?history=true`).then(history=>{if(!cancelled)setSourceHistory(history.filter(s=>s.logical_key===source.logical_key).sort((a,b)=>b.version-a.version))}).catch(()=>{});return()=>{cancelled=true}},[inspect?.source?.logical_key,inspect?.source?.project_id]);
 const importUrl=(event:FormEvent)=>{event.preventDefault();void perform('url',async()=>{await post(`/projects/${projectId}/urls`,{url:sourceDraft.url,competitor:sourceDraft.competitor});await refresh(projectId);setModal(null);notify('网页原文已保存到资料库')})};
 const selectProject=(id:string)=>{setProjectId(id);setPage(projects.find(p=>p.id===id)?.latest_report_id?'report':'overview');setSidebarOpen(false);setError('')};
 const seedDemo=()=>perform('demo',async()=>{const p=await post<Project>('/demo',{},true);await loadProjects();setProjectId(p.id);setPage('overview');notify('演示工作区已创建，30 份虚构资料已就绪')});
 const openBrief=()=>{if(!project)return;setDraft({title:project.title,question:project.question,audience:project.audience,time_range:project.time_range??'最近12个月',web_enabled:project.web_enabled??project.mode==='public',mode:project.mode,competitors:project.competitors.join('，'),dimensions:project.dimensions.join('，')});setError('');setModal('brief')};
 const saveBrief=(event:FormEvent)=>{event.preventDefault();void perform('save',async()=>{const competitors=splitList(draft.competitors);if(!competitors.length||competitors.length>4)throw new Error('请输入 1–4 家竞品，以逗号分隔');const data={title:draft.title,question:draft.question,audience:draft.audience,time_range:draft.time_range,web_enabled:draft.mode==='public'&&draft.web_enabled,competitors,dimensions:splitList(draft.dimensions),...(modal==='create'?{mode:draft.mode}:{})};if(!data.dimensions.length)throw new Error('至少需要一个研究维度');const p=modal==='create'?await post<Project>('/projects',data):await api<Project>(`/projects/${projectId}`,{method:'PATCH',body:JSON.stringify(data)});await loadProjects();if(p.id===projectId)await refresh(p.id);else setProjectId(p.id);setModal(null);setPage('overview');notify('研究需求已保存')})};
 const prepareRun=()=>perform('outline',async()=>{if(!project)return;const o=await post<Outline>(`/projects/${projectId}/outline`);setOutline(o);setModelProfile('gemini-budget');setMode(project.mode==='synthetic'?'replay':'live');setRunBudget(String(o.estimated_cap_usd));setModal('outline')});
 const startRun=()=>perform('start',async()=>{if(!outline)return;const dimensions=splitList(outline.dimensions.join('，'));if(JSON.stringify(dimensions)!==JSON.stringify(project?.dimensions))await api(`/projects/${projectId}`,{method:'PATCH',body:JSON.stringify({dimensions})});const next=await post<Run>(`/projects/${projectId}/runs`,{mode,model_profile:modelProfile,architecture,budget_usd:Number(runBudget),bucket:project?.mode==='public'&&(project.web_enabled??true)?'web':'development'},true);await refresh(projectId);setRunId(next.id);setModal(null);setPage('collaboration')});
 const controlRun=(action:'cancel'|'resume')=>perform(action,async()=>{if(!run)return;const next=await post<Run>(`/runs/${run.id}/${action}`);await refresh(projectId);setRunId(next.id);notify(action==='cancel'?'已请求取消；已完成结果会保留':'研究已恢复，将复用已完成的任务')});
 const upload=(files:FileList|null)=>{if(!files?.length)return;void perform('upload',async()=>{for(const file of Array.from(files)){const data=new FormData();data.append('file',file);if(sourceFilter)data.append('competitor',sourceFilter);await api(`/projects/${projectId}/upload`,{method:'POST',body:data})}await refresh(projectId);notify(`已导入 ${files.length} 份资料`);if(uploadRef.current)uploadRef.current.value=''})};
 const openSourceForm=(source?:Source)=>{setInspect(null);setError('');setReplacing(source??null);setSourceDraft(source?{title:source.title,text:source.text,competitor:source.competitor,kind:source.kind,published_at:source.published_at?.slice(0,10)??'',url:source.url??''}:{title:'',text:'',competitor:sourceFilter,kind:'document',published_at:'',url:''});setModal(source?'replace':'addSource')};
 const saveSource=(event:FormEvent)=>{event.preventDefault();void perform('source',async()=>{await post(`/projects/${projectId}/sources`,{...sourceDraft,published_at:sourceDraft.published_at||null,url:sourceDraft.url||null,...(replacing?{logical_key:replacing.logical_key}:{})});await refresh(projectId);setModal(null);setInspect(null);notify(replacing?'资料新版本已保存，相关结论将在下次研究时重新核查':'资料已加入证据库')})};
 const revise=(event:FormEvent)=>{event.preventDefault();void perform('revise',async()=>{if(!report)return;const next=await post<Run>(`/reports/${report.id}/revise`,{instructions:revision});await refresh(projectId);setRunId(next.id);setModal(null);setRevision('');setPage('collaboration')})};
 const exportReport=(format:'docx'|'pptx')=>perform(`export-${format}`,async()=>{if(!report)return;const job=await post<ExportJob>(`/reports/${report.id}/exports`,{format});setExportJobs(old=>[job,...old.filter(j=>j.id!==job.id)]);notify(job.status==='completed'?'文件已生成，可以下载':'正在生成文件，完成后可在此下载')});
 const showClaims=(ids:string[])=>{if(!report)return;setInspect({claims:report.claims.filter(c=>ids.includes(c.id))})};
 const showEvidence=(evidence:Evidence)=>{const source=report?.sources.find(s=>s.id===evidence.source_id)??sources.find(s=>s.id===evidence.source_id);if(source)setInspect({source,quote:evidence.quote});else setError('该证据原文暂不可用')};
 const showCollaborationSource=(sourceId:string)=>{const known=reports.flatMap(item=>item.sources).find(source=>source.id===sourceId)??sources.find(source=>source.id===sourceId);if(known){setInspect({source:known});return;}void perform('evidence',async()=>{const history=await api<Source[]>(`/projects/${projectId}/sources?history=true`);const source=history.find(item=>item.id===sourceId);if(!source)throw new Error('这条核查记录所用的资料版本暂不可用');setInspect({source})})};
 const sourceList=sources.filter(s=>(!sourceFilter||s.competitor===sourceFilter)&&`${s.title} ${s.text}`.toLowerCase().includes(sourceQuery.toLowerCase()));
 const done=tasks.filter(t=>t.status==='completed').length;

 return <div className="app-shell">
  {sidebarOpen&&<div className="sidebar-scrim" onClick={()=>setSidebarOpen(false)}/>}
  <aside className={`sidebar ${sidebarOpen?'open':''}`}>
   <a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('overview')}}><span className="brand-mark"><Leaf size={24}/></span><span>BriefForge<span className="brand-dot">.</span></span></a>
   <div className="workspace-label"><span>RESEARCH WORKSPACE</span><Badge tone="green">个人版</Badge></div>
   <div className="project-select"><FolderOpen size={17}/><select aria-label="选择研究项目" value={projectId} onChange={e=>selectProject(e.target.value)}>{!projects.length&&<option value="">我的研究空间</option>}{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><ChevronDown size={14}/></div>
   <button className="new-project" onClick={()=>{setDraft(initialDraft);setModal('create')}}><Plus size={16}/>创建研究项目</button>
   <div className="nav-label">工作台</div>
   <nav aria-label="工作台导航">{nav.map(item=><button className={`nav-item ${page===item.id?'selected':''}`} key={item.id} onClick={()=>{setPage(item.id);setSidebarOpen(false)}}><item.icon size={18}/><span>{item.label}</span>{item.id==='sources'&&sources.length>0&&<small>{sources.length}</small>}{item.id==='collaboration'&&active&&<span className="live-dot"/>}{page===item.id&&<ChevronRight className="nav-arrow" size={15}/>}</button>)}</nav>
   <div className="sidebar-note"><div className="tiny-stars"><Sparkles size={18}/></div><h4>让每个结论，都有依据。</h4><p>多个专业 Agent 协作，<br/>从零散资料到完整洞察。</p><button onClick={()=>void seedDemo()} disabled={!!busy}><span>{busy==='demo'?'正在准备资料…':'体验内置案例'}</span><ArrowUpRight size={15}/></button></div>
   <div className="sidebar-bottom"><div className="budget-title"><Wallet size={15}/><span>模型总预算</span><b>{money(budget?.spent_usd)}</b></div><div className="budget-track"><i style={{width:`${Math.min(100,((budget?.spent_usd??0)+(budget?.reserved_usd??0))/(budget?.limit_usd??10)*100)}%`}}/></div><p>上限 ${(budget?.limit_usd??10).toFixed(2)}<span>预留 {money(budget?.reserved_usd)}</span></p><div className="profile"><div className="avatar">研</div><div><strong>我的研究工作台</strong><small>证据优先 · 透明协作</small></div><ShieldCheck size={17}/></div></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-menu" aria-label="打开菜单" onClick={()=>setSidebarOpen(true)}><Menu size={21}/></button><span>工作空间</span><ChevronRight size={14}/><strong>{project?.title??'新研究，从这里开始'}</strong></div><div className="topbar-right"><span className="saved-state"><span className="status-dot"/>{active?'协作进行中':'本地工作区'}</span><a href="https://github.com/OpenRouterTeam" target="_blank" rel="noreferrer" className="icon-button help-button" title="OpenRouter"><CircleHelp size={18}/></a><div className="avatar small">研</div></div></header>
   <main>
    {error&&<div className="error-banner" role="alert"><AlertTriangle size={18}/><span>{error}</span><button className="icon-button" aria-label="关闭错误提示" onClick={()=>setError('')}><X size={17}/></button></div>}
    {loading?<div className="loading-screen"><Loader2 className="spin" size={25}/><p>正在打开研究工作区…</p></div>:!project?<>
     <section className="welcome"><div className="eyebrow"><span/>FROM EVIDENCE TO INSIGHT</div><h1>好研究，<br/>从一个好问题开始。</h1><p>把搜集、分析与核查交给协作的 Agent。<br/>将分散的资料，变成有据可查的研究成果。</p><div className="welcome-actions"><Button variant="primary" onClick={()=>{setDraft(initialDraft);setModal('create')}}><Plus size={17}/>创建我的研究</Button><Button onClick={()=>void seedDemo()} disabled={!!busy}>{busy==='demo'?<Loader2 className="spin" size={17}/>:<Play size={16}/>}体验内置案例</Button></div><div className="welcome-foot"><ShieldCheck size={14}/>证据可追溯<span>·</span>支持 Word / PPT<span>·</span>费用全程可见</div></section>
     <div className="welcome-cards"><div><span className="card-number">01 / RESEARCH</span><Network size={25}/><h3>专业分工，共同研究</h3><p>协调、行业、竞品、商业、核查与编辑六种角色，让研究形成真正的协作闭环。</p></div><div><span className="card-number">02 / VERIFY</span><ShieldCheck size={25}/><h3>从结论，回到原文</h3><p>保留来源、版本与引用。发现冲突时补充调查，无法确认时明确留下未知。</p></div><div><span className="card-number">03 / DELIVER</span><FileCheck2 size={25}/><h3>可读，也可交付</h3><p>同一份研究生成可编辑的报告与演示文稿，让证据跟随每一次交付。</p></div></div>
    </>:<>
     <div className="page-heading"><div><div className="eyebrow">{page==='report'?'RESEARCH DELIVERABLE':page==='sources'?'EVIDENCE LIBRARY':page==='collaboration'?'AGENT COLLABORATION':'RESEARCH OVERVIEW'}</div><h1>{nav.find(n=>n.id===page)?.label}</h1><p>{page==='overview'?'明确问题、汇集资料，让研究有序开始。':page==='sources'?'好的判断，始于可靠的资料。所有证据保留来源与版本。':page==='collaboration'?'每一次分工、发现与补查，都在这里留下记录。':'将可靠的证据，组织成清晰、可交付的判断。'}</p></div><div className="heading-actions">{project.mode==='synthetic'?<Badge tone="amber"><Leaf size={12}/>虚构测试资料</Badge>:<Badge tone="green"><Globe2 size={12}/>真实资料研究</Badge>}{page==='report'&&report?<Button onClick={()=>{setRevision('');setModal('revise')}} disabled={active}><MessageSquareText size={16}/>追问与修改</Button>:page==='sources'?<Button variant="primary" onClick={()=>uploadRef.current?.click()} disabled={!!busy||active}><Upload size={16}/>导入资料</Button>:<Button variant="primary" disabled={!!busy||active} onClick={()=>void prepareRun()}>{busy==='outline'?<Loader2 className="spin" size={16}/>:<Play size={15}/>}开始研究</Button>}</div></div>
     {project.dirty&&<div className="notice-banner"><RefreshCw size={16}/><span>资料或需求已有更新。下次研究将重新核查受影响的结论，已有报告保留原版本。</span>{!active&&<button onClick={()=>void prepareRun()}>更新研究<ArrowRight size={14}/></button>}</div>}
     {page==='overview'&&<>
      <section className="overview-hero"><div className="hero-copy"><div className="eyebrow light">YOUR NEXT RESEARCH</div><h2>{project.title}</h2><p>{project.question}</p><div className="hero-tags"><span><BookOpen size={14}/>{project.audience}</span><span><Layers3 size={14}/>{project.competitors.length} 家竞品</span><span><Clock3 size={14}/>{project.time_range??'最近12个月'}</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="orbit-center"><Leaf size={31}/></div><span className="orbit-point point-one"><Search size={17}/></span><span className="orbit-point point-two"><ShieldCheck size={19}/></span><span className="orbit-point point-three"><FileText size={17}/></span></div></section>
      <div className="stat-grid"><Stat label="研究资料" value={sources.length} unit="份" icon={FolderOpen} note="保留来源与历史版本"/><Stat label="研究维度" value={project.dimensions.length} unit="项" icon={Layers3} note="围绕你的研究目标"/><Stat label="报告版本" value={reports.length} unit="版" icon={BookOpen} note={report?`最近更新 ${date(report.created_at)}`:'完成研究后自动保存'}/><Stat label="本项目模型费用" value={money(runs.reduce((sum,r)=>sum+r.spent_usd,0))} icon={Wallet} note="固定响应回放不产生模型费用"/></div>
      <div className="overview-columns"><section className="panel"><div className="panel-header"><div><h3>研究简报</h3><p>为 Agent 设定清晰的研究边界</p></div><Button variant="ghost" onClick={openBrief} disabled={active}><Settings2 size={15}/>编辑</Button></div><div className="brief-content"><div className="brief-row"><span>研究问题</span><p>{project.question}</p></div><div className="brief-row"><span>目标读者</span><p>{project.audience}</p></div><div className="brief-row"><span>研究范围</span><p>{project.time_range??'最近12个月'}</p></div>{project.mode==='public'&&<div className="brief-row"><span>资料获取</span><p>{(project.web_enabled??true)?'已导入资料 + 联网搜索公开资料':'仅分析已导入资料 · 使用真实模型'}</p></div>}<div className="brief-row"><span>比较对象</span><div className="pill-row">{project.competitors.map(c=><span className="competitor-pill" key={c}><span/>{c}</span>)}</div></div><div className="brief-row"><span>研究维度</span><div className="pill-row">{project.dimensions.map(d=><Badge key={d}>{d}</Badge>)}</div></div></div><div className="panel-footer"><ShieldCheck size={15}/><span>最多 3 个任务并行 · 问题最多补查 2 轮 · 费用受预算约束</span></div></section><section className="panel getting-started"><div className="panel-header"><div><h3>研究准备</h3><p>从问题到成果，只需三步</p></div><span className="step-fraction">{sources.length?2:1}/3</span></div><PreparationStep number="01" title="明确你的研究目标" body="设置比较对象与研究维度" complete/><PreparationStep number="02" title="汇集相关研究资料" body={sources.length?`${sources.length} 份资料已准备就绪`:'上传文件，或添加原文资料'} complete={sources.length>0}/><PreparationStep number="03" title="确认大纲，启动协作" body={active?'Agent 正在分工研究':report?'已有研究成果，可继续深入':'先审阅研究大纲，再开始分析'} complete={!!report}/><Button variant="primary" className="full-width" disabled={!!busy||active} onClick={()=>void prepareRun()}>确认研究大纲<ArrowRight size={16}/></Button>{active&&<button className="text-link" onClick={()=>setPage('collaboration')}>查看协作进度<ArrowRight size={14}/></button>}</section></div>
      {runs.length>0&&<section className="panel history-panel"><div className="panel-header"><div><h3>研究记录</h3><p>每次研究的状态、方式与实际费用</p></div><Badge>{runs.length} 次研究</Badge></div><div className="history-list">{runs.slice(0,6).map(r=><button key={r.id} onClick={()=>{setRunId(r.id);setPage('collaboration')}}><span className={`run-status-icon ${r.status}`}><GitBranch size={18}/></span><div><strong>{r.instructions?'补充研究与修订':'竞品与行业研究'}</strong><small>{date(r.created_at)} · {r.mode==='replay'?'固定响应回放':`真实模型 · ${r.model_profile==='gemini-budget'?'Gemini budget':'Qwen'}`} · {r.architecture==='multi'?'动态多 Agent':r.architecture==='single'?'单 Agent':'固定流水线'}</small></div><Badge tone={r.status==='completed'?'green':r.status==='failed'?'red':'neutral'}>{statusLabel(r.status)}</Badge><span className="history-cost">{money(r.spent_usd)}</span><ChevronRight size={16}/></button>)}</div></section>}
     </>}
     {page==='sources'&&<>
      <input ref={uploadRef} type="file" className="hidden" multiple accept=".csv,.xlsx,.docx,.pdf,.html,.htm,.txt,.md" onChange={e=>upload(e.target.files)}/>
      <div className="source-toolbar"><div className="search-input"><Search size={17}/><input aria-label="搜索资料" placeholder="搜索资料名称或内容…" value={sourceQuery} onChange={e=>setSourceQuery(e.target.value)}/></div><select aria-label="筛选竞品资料" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">所有比较对象</option>{project.competitors.map(c=><option key={c}>{c}</option>)}</select>{project.mode==='public'&&<Button onClick={()=>{setSourceDraft({...sourceDraft,url:'',competitor:sourceFilter});setError('');setModal('url')}} disabled={active}><Globe2 size={16}/>导入网页</Button>}<Button onClick={()=>openSourceForm()} disabled={active}><FilePlus2 size={16}/>添加原文</Button></div>
      <div className="sources-layout"><section className="panel source-panel"><div className="panel-header"><h3>资料库 <span className="count-text">{sourceList.length}</span></h3><span className="muted">当前有效版本</span></div>{sourceList.length?<div className="source-list">{sourceList.map(s=><button key={s.id} className="source-card" onClick={()=>setInspect({source:s})}><span className={`file-icon ${s.kind==='pricing'?'amber':''}`}><FileText size={22}/></span><div className="source-card-copy"><h4>{s.title}</h4><p><span>{s.competitor||'行业与背景'}</span><span>·</span><span>{day(s.published_at)}</span><span>·</span><span>版本 {s.version}</span></p><div className="source-excerpt">{s.text.slice(0,100)}</div></div><div className="source-card-end"><Badge tone={s.synthetic?'amber':'green'}>{s.synthetic?'虚构资料':s.url?'网页来源':'上传资料'}</Badge><ChevronRight size={16}/></div></button>)}</div>:<Empty icon={FolderOpen} title={sourceQuery?'没有找到匹配资料':'先为研究准备一些资料'} body="支持 PDF、Word、Excel、CSV、HTML 和文本资料。也可以直接粘贴原文。"><Button onClick={()=>openSourceForm()}><Plus size={15}/>添加资料</Button></Empty>}</section><aside className="source-info"><div className="info-card"><ShieldCheck size={23}/><h3>让证据始终可追溯</h3><p>每份资料保留获取时间、来源链接与原文。报告中的引用会定位到研究时使用的版本。</p><ul><li><Check size={14}/>引用保留原文片段</li><li><Check size={14}/>更新资料后保留旧版本</li><li><Check size={14}/>未披露日期会明确标识</li></ul></div><div className="upload-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!active&&!busy)upload(e.dataTransfer.files)}}><Upload size={24}/><h4>{busy==='upload'?'正在导入资料…':'拖放文件到这里'}</h4><p>PDF · DOCX · XLSX · CSV<br/>HTML · TXT · MD</p><button onClick={()=>uploadRef.current?.click()} disabled={active||!!busy}>或选择文件</button></div><p className="source-caution">仅支持文本型 PDF，扫描件请先转换为文字。{sourceFilter&&`当前导入资料将归属「${sourceFilter}」。`}</p></aside></div>
     </>}
     {page==='collaboration'&&<>
      {!run?<section className="panel"><Empty icon={Network} title="你的研究团队，准备就绪" body="确认研究大纲后，Agent 将围绕问题分工研究、核查证据并组织报告。"><Button variant="primary" onClick={()=>void prepareRun()}>确认大纲并开始<ArrowRight size={16}/></Button></Empty></section>:<>
       <section className="run-summary panel"><div className="run-summary-top"><div className="run-heading"><span className={`run-status-icon ${run.status}`}>{activeRun(run.status)?<Loader2 className="spin" size={23}/>:run.status==='completed'?<CheckCheck size={23}/>:<GitBranch size={23}/>}</span><div><h3>{statusLabel(run.status)}<Badge tone={run.mode==='replay'?'amber':'green'}>{run.mode==='replay'?'固定响应回放':`真实模型 · ${run.model_profile==='gemini-budget'?'Gemini budget':'Qwen'}`}</Badge></h3><p>{run.mode==='replay'?'根据内置材料演示协作逻辑，不调用真实模型。':`使用 ${run.model_profile==='gemini-budget'?'Gemini budget':'Qwen'} 配置；所有尝试与重试均计入费用。`}</p></div></div><div className="run-controls"><select aria-label="选择研究记录" value={run.id} onChange={e=>setRunId(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{date(r.created_at)} · {statusLabel(r.status)}</option>)}</select>{activeRun(run.status)?<Button onClick={()=>void controlRun('cancel')} disabled={!!busy}><Pause size={15}/>取消研究</Button>:['failed','cancelled','budget_exceeded'].includes(run.status)?<Button onClick={()=>void controlRun('resume')} disabled={!!busy||active}><RefreshCw size={15}/>恢复研究</Button>:<Button onClick={()=>{setReportId(run.report_id??'');setPage('report')}}><BookOpen size={15}/>查看报告</Button>}</div></div><div className="run-metrics"><div><small>任务完成</small><strong>{done}<span> / {tasks.length}</span></strong></div><div><small>本次费用 / 上限</small><strong>{money(run.spent_usd)}<span> / ${run.budget_usd.toFixed(2)}</span></strong></div><div><small>模型请求</small><strong>{run.request_count}<span> / 40 次</span></strong></div><div><small>执行架构</small><strong className="metric-text">{run.architecture==='multi'?'动态多 Agent':run.architecture==='single'?'单 Agent 基线':'固定流水线'}</strong></div></div><div className="run-progress"><span style={{width:`${tasks.length?done/tasks.length*100:0}%`}}/></div>{run.error&&<div className="run-error"><AlertTriangle size={16}/>{run.error}</div>}</section>
       <CollaborationImpact runId={run.id} running={activeRun(run.status)} detailed onSource={showCollaborationSource}/>
       <div className="collaboration-layout"><section><div className="section-heading"><h3>协作任务</h3><span><span className="status-dot"/>最多 3 个任务同时执行</span></div><div className="task-list">{tasks.length?tasks.map((t,index)=><div className={`task-card ${t.status}`} key={t.id}><div className="task-icon">{t.status==='completed'?<Check size={19}/>:t.status==='running'?<Loader2 className="spin" size={19}/>:t.status==='failed'?<AlertTriangle size={19}/>:<span>{String(index+1).padStart(2,'0')}</span>}</div><div className="task-copy"><div><span className="task-role">{roleLabels[t.role]??t.role}</span>{t.round>0&&<Badge tone="amber">第 {t.round} 轮补查</Badge>}<span className={`task-state ${t.status}`}>{statusLabel(t.status)}</span></div><h4>{t.title}</h4>{t.target&&<p>{t.target}</p>}{t.error&&<p className="red-text">{t.error}</p>}<details><summary>任务详情<ChevronDown size={13}/></summary><p>依赖任务：{t.depends_on.length} 项 · 最后更新 {date(t.updated_at)}</p>{Object.keys(t.output??{}).length>0&&<pre>{JSON.stringify(t.output,null,2)}</pre>}</details></div></div>):<div className="panel"><Empty icon={GitBranch} title="正在准备任务" body="研究启动后，任务分工将在这里逐项展开。"/></div>}</div></section><section className="panel event-panel"><div className="panel-header"><h3>研究日志</h3><Badge>{events.length} 条</Badge></div><div className="event-list">{events.length?events.slice().reverse().map(event=><div className={`event-item ${event.type}`} key={`${event.run_id}:${event.id}`}><span className="event-dot"/><div><time>{date(event.created_at)}</time><p>{event.message}</p><small>{event.type}</small></div></div>):<p className="muted">等待第一条研究记录…</p>}</div><div className="panel-footer"><ShieldCheck size={14}/><span>日志已持久化，断开连接后可恢复。</span></div></section></div>
      </>}
     </>}
     {page==='report'&&<>
      {!report?<section className="panel"><Empty icon={BookOpen} title={active?'你的研究报告正在形成':'把问题，变成一份好报告'} body={active?'Agent 正在研究与核查。完成后，报告会自动出现在这里。':'从资料开始，完成一次研究后即可审阅结论、追溯证据，并导出 Word 与 PPT。'}><Button variant="primary" onClick={()=>active?setPage('collaboration'):void prepareRun()}>{active?'查看协作进度':'开始我的研究'}<ArrowRight size={16}/></Button></Empty></section>:<>
       <div className="report-toolbar"><div><span className="document-status"><CheckCircle2 size={15}/>已保存报告</span><span className="toolbar-divider"/><select aria-label="选择报告版本" value={report.id} onChange={e=>setReportId(e.target.value)}>{reports.map(r=><option key={r.id} value={r.id}>版本 {r.version} · {date(r.created_at)}</option>)}</select><Badge tone={report.mode==='replay'?'amber':'green'}>{report.mode==='replay'?'固定响应回放':'真实模型'}</Badge></div><div><Button disabled={!!busy} onClick={()=>void exportReport('docx')}>{busy==='export-docx'?<Loader2 className="spin" size={16}/>:<FileText size={16}/>}导出 Word</Button><Button variant="primary" disabled={!!busy} onClick={()=>void exportReport('pptx')}>{busy==='export-pptx'?<Loader2 className="spin" size={16}/>:<Presentation size={16}/>}导出 PPT<ArrowDownToLine size={14}/></Button></div></div>
       {exportJobs.filter(j=>j.report_id===report.id).map(job=><div key={job.id} className={`export-notice ${job.status==='failed'?'failed':''}`}><span>{job.status==='completed'?<CheckCircle2 size={17}/>:job.status==='failed'?<AlertTriangle size={17}/>:<Loader2 className="spin" size={17}/>}<strong>{job.format.toUpperCase()}</strong>{job.status==='completed'?`已生成 · 报告版本 ${report.version}`:job.error??'正在生成文档…'}</span>{job.status==='completed'&&<a className="text-link" href={job.download_url??`/api/exports/${job.id}/download`} download>下载文件<ArrowDownToLine size={14}/></a>}</div>)}
       <CollaborationImpact runId={report.run_id} onSource={showCollaborationSource}/>
       <div className="report-layout"><article className="report-document"><div className="document-topline"><span>BRIEFFORGE RESEARCH</span><span>VOL. {String(report.version).padStart(2,'0')}</span></div><header className="document-header"><div className="report-category"><span/>行业与竞品研究</div><h1>{report.title}</h1><p>为 {project.audience} 准备的研究简报</p><div className="document-meta"><span><Clock3 size={13}/>{day(report.created_at)}</span><span><FolderOpen size={13}/>{report.sources.length} 份研究资料</span><span><ShieldCheck size={13}/>{report.claims.length} 项结论</span></div></header>{report.synthetic&&<div className="synthetic-note"><Leaf size={15}/><span>本报告使用虚构测试资料，仅用于展示研究流程。<strong>{report.mode==='replay'?' 本次为固定响应回放。':''}</strong></span></div>}{report.mode==='live'&&<div className="live-draft-note"><FileText size={15}/><span>真实模型生成的研究草稿。交付前请核对关键结论与来源。</span></div>}<section id="summary" className="report-section"><div className="report-section-label">01 / EXECUTIVE SUMMARY</div><h2>核心摘要</h2><div className="executive-summary"><span className="summary-mark">“</span><p>{report.executive_summary}</p></div></section>
        {report.comparison.length>0&&<section id="comparison" className="report-section"><div className="report-section-label">02 / COMPETITIVE LANDSCAPE</div><h2>竞品对比，一目了然</h2><p className="section-caption">保留价格条件与套餐限制，点击证据查看判断依据。</p><div className="comparison-scroll"><table className="comparison-table"><thead><tr><th>比较维度</th>{report.comparison.map(c=><th key={c.competitor}><span className="company-dot"/>{c.competitor}</th>)}</tr></thead><tbody>{([['定位与目标客户','positioning'],['价格与计费','price'],['SSO 支持','sso']] as const).map(([label,key])=><tr key={key}><th>{label}</th>{report.comparison.map(c=><td key={c.competitor}>{c[key]||'未披露'}</td>)}</tr>)}<tr><th>条件与说明</th>{report.comparison.map(c=><td key={c.competitor} className="condition-cell">{c.conditions.length?c.conditions.join('；'):'未披露'}</td>)}</tr><tr><th>证据依据</th>{report.comparison.map(c=><td key={c.competitor}><button className="evidence-link" onClick={()=>showClaims(c.claim_ids)}><Link2 size={13}/>{c.claim_ids.length} 项结论<ArrowUpRight size={12}/></button></td>)}</tr></tbody></table></div></section>}
        {report.sections.map((section,index)=><section id={`section-${section.id}`} className="report-section" key={section.id}><div className="report-section-label">{String(index+3).padStart(2,'0')} / RESEARCH FINDINGS</div><h2>{section.heading}</h2><p className="section-body">{section.body}</p>{section.claim_ids.length>0&&<button className="evidence-link section-evidence" onClick={()=>showClaims(section.claim_ids)}><Link2 size={14}/>查看 {section.claim_ids.length} 项结论与引用<ArrowUpRight size={13}/></button>}</section>)}
        {report.unresolved.length>0&&<section id="unresolved" className="report-section"><div className="report-section-label">OPEN QUESTIONS</div><h2>尚待确认的问题</h2><div className="unresolved-box"><AlertTriangle size={19}/><div><strong>证据的边界，也是结论的一部分。</strong><ul>{report.unresolved.map((item,i)=><li key={i}>{item}</li>)}</ul></div></div></section>}
        {report.changes.length>0&&<section className="report-section changes-section"><h3><GitBranch size={17}/>本版本的核查与变化</h3><ul>{report.changes.map((change,i)=><li key={i}>{change}</li>)}</ul></section>}
        <footer className="document-footer"><span className="document-brand"><Leaf size={15}/>BriefForge</span><p>每个结论，都应有迹可循。</p><span>版本 {report.version}</span></footer>
       </article><aside className="report-aside"><div className="toc"><span className="nav-label">报告目录</span><a href="#summary" className="toc-first">核心摘要<ArrowUpRight size={13}/></a>{report.comparison.length>0&&<a href="#comparison">竞品对比</a>}{report.sections.map(s=><a key={s.id} href={`#section-${s.id}`}>{s.heading}</a>)}{report.unresolved.length>0&&<a href="#unresolved">尚待确认的问题</a>}</div><div className="evidence-summary"><div className="evidence-summary-icon"><ShieldCheck size={22}/></div><h4>研究透明度</h4><div><span>有证据支持</span><strong>{report.claims.filter(c=>c.status==='supported').length}</strong></div><div><span>有待确认 / 冲突</span><strong>{report.claims.filter(c=>c.status!=='supported').length}</strong></div><div><span>引用资料</span><strong>{report.sources.length}</strong></div><button onClick={()=>setInspect({claims:report.claims})}>查看全部结论<ArrowRight size={14}/></button></div><div className="revision-card"><MessageSquareText size={20}/><h4>让研究再深入一步</h4><p>补充一个问题，或调整报告的重点。</p><Button onClick={()=>setModal('revise')} disabled={active}><Plus size={14}/>补充研究</Button></div><p className="snapshot-note"><CheckCheck size={13}/>Word 与 PPT 使用相同报告版本，导出不额外调用模型。</p></aside></div>
      </>}
     </>}
    </>}
    <footer className="workspace-footer"><span>BriefForge · Research with evidence.</span><span>清晰的判断，源于透明的过程。</span></footer>
   </main>
  </div>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}

  {(modal==='create'||modal==='brief')&&<Modal error={error} title={modal==='create'?'创建一个研究项目':'编辑研究简报'} description="一个清晰的问题，是一份好研究的起点。" onClose={()=>setModal(null)} wide><form onSubmit={saveBrief}><Field label="项目名称"><input required maxLength={120} autoFocus placeholder="例如：中小企业协作工具竞品研究" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="你想研究什么？"><textarea required minLength={5} maxLength={6000} rows={4} placeholder="描述你的决策背景、研究问题，以及希望得到什么答案…" value={draft.question} onChange={e=>setDraft({...draft,question:e.target.value})}/></Field><Field label="研究时间范围" hint="例如：最近12个月，或2026年1月至9月；未披露时间的来源仍会明确标注。"><input required maxLength={200} value={draft.time_range} onChange={e=>setDraft({...draft,time_range:e.target.value})}/></Field><div className="form-grid"><Field label="报告面向谁"><input required value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value})}/></Field><Field label="比较对象" hint="1–4 家竞品，用逗号分隔"><input required placeholder="竞品 A，竞品 B，竞品 C" value={draft.competitors} onChange={e=>setDraft({...draft,competitors:e.target.value})}/></Field></div><Field label="研究维度" hint="用逗号分隔；启动前可再次确认"><input required value={draft.dimensions} onChange={e=>setDraft({...draft,dimensions:e.target.value})}/></Field>{modal==='create'&&<div className="field"><span>资料工作区</span><div className="option-cards"><button type="button" className={draft.mode==='public'?'chosen':''} onClick={()=>setDraft({...draft,mode:'public',web_enabled:draft.mode==='public'?draft.web_enabled:true})}><Globe2 size={20}/><strong>真实资料研究</strong><small>上传资料并使用真实模型，可联网搜集公开资料</small></button><button type="button" className={draft.mode==='synthetic'?'chosen':''} onClick={()=>setDraft({...draft,mode:'synthetic',web_enabled:false})}><Leaf size={20}/><strong>虚构测试工作区</strong><small>资料始终带测试标识；内置案例支持固定响应回放</small></button></div></div>}{draft.mode==='public'&&<div className="web-source-setting"><label className="checkbox-row"><input type="checkbox" checked={draft.web_enabled} onChange={e=>setDraft({...draft,web_enabled:e.target.checked})}/><span>联网搜索公开资料</span></label><p>关闭后只分析已导入资料，仍使用真实模型完成研究；适合仅基于上传文件的研究。</p></div>}<div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>取消</Button><Button variant="primary" disabled={!!busy}>{busy==='save'?<Loader2 className="spin" size={15}/>:<Check size={15}/>}保存研究简报</Button></div></form></Modal>}
  {modal==='outline'&&outline&&<Modal error={error} title="确认研究大纲" description="确认研究方向后，专业 Agent 将开始分工协作。" onClose={()=>setModal(null)} wide><div className="outline-questions">{outline.questions.map((q,index)=><div key={index}><span>{String(index+1).padStart(2,'0')}</span><p>{q}</p></div>)}</div><Field label="比较维度" hint="用逗号分隔，可按决策需要调整"><input value={outline.dimensions.join('，')} onChange={e=>setOutline({...outline,dimensions:e.target.value.split(/[,，]/)})}/></Field><div className="form-grid"><Field label="运行方式"><select value={mode} onChange={e=>setMode(e.target.value as 'replay'|'live')}>{project?.mode==='synthetic'&&<option value="replay">固定响应回放 · 不调用模型</option>}<option value="live">真实模型 · OpenRouter</option></select></Field><Field label="本次费用上限（USD）"><input type="number" step="0.01" min="0.01" max="0.30" value={runBudget} onChange={e=>setRunBudget(e.target.value)}/></Field></div><div className="outline-note"><ShieldCheck size={18}/><p>{mode==='replay'?'回放用于展示内置案例的协作流程，界面与导出将明确标识，不产生模型费用。':'模型调用与重试计入预算，费用未知时保留预留额。达到预算上限后暂停研究。'}</p></div>{mode==='live'&&<p className="outline-model-note">本次模型：<strong>{modelProfile==='gemini-budget'?'Gemini budget · 推荐 / 经实测':'Qwen · 实验线路'}</strong> · 可在高级设置中选择</p>}<button className="advanced-toggle" type="button" onClick={()=>setAdvanced(!advanced)}><Settings2 size={14}/>高级设置<ChevronDown size={14}/></button>{advanced&&<><Field label="模型配置" hint="Gemini budget 已完成项目内实测；Qwen 为实验线路。只使用明确选择的配置，不会自动切换。"><select value={modelProfile} onChange={e=>setModelProfile(e.target.value as typeof modelProfile)}><option value="gemini-budget">Gemini budget · 推荐 / 经实测</option><option value="qwen-default">Qwen · 实验线路</option></select></Field><Field label="执行架构（对照评测）"><select value={architecture} onChange={e=>setArchitecture(e.target.value as typeof architecture)}><option value="multi">动态多 Agent：支持核查与补查</option><option value="single">单 Agent 基线</option><option value="pipeline">固定流水线</option></select></Field></>}<div className="modal-actions"><Button onClick={()=>setModal(null)}>稍后开始</Button><Button variant="primary" disabled={!!busy||!outline.dimensions.some(d=>d.trim())||!Number(runBudget)||Number(runBudget)>0.30} onClick={()=>void startRun()}>{busy==='start'?<Loader2 className="spin" size={16}/>:<Play size={15}/>}确认并开始研究</Button></div></Modal>}
  {(modal==='addSource'||modal==='replace')&&<Modal error={error} title={replacing?'更新资料版本':'添加研究资料'} description={replacing?'保留历史版本，相关结论将在下次研究中重新核查。':'粘贴完整原文，让每个引用都有据可查。'} onClose={()=>setModal(null)} wide><form onSubmit={saveSource}><Field label="资料标题"><input required value={sourceDraft.title} onChange={e=>setSourceDraft({...sourceDraft,title:e.target.value})}/></Field><div className="form-grid"><Field label="资料归属"><select value={sourceDraft.competitor} onChange={e=>setSourceDraft({...sourceDraft,competitor:e.target.value})}><option value="">行业与背景</option>{project?.competitors.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="发布日期（可选）"><input type="date" value={sourceDraft.published_at} onChange={e=>setSourceDraft({...sourceDraft,published_at:e.target.value})}/></Field></div><Field label="来源链接（可选）"><input type="url" placeholder="https://…" value={sourceDraft.url} onChange={e=>setSourceDraft({...sourceDraft,url:e.target.value})}/></Field><Field label="资料原文"><textarea required rows={10} value={sourceDraft.text} onChange={e=>setSourceDraft({...sourceDraft,text:e.target.value})}/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>取消</Button><Button variant="primary" disabled={!!busy}><Check size={16}/>{replacing?'保存为新版本':'添加到资料库'}</Button></div></form></Modal>}
  {modal==='url'&&<Modal error={error} title="导入公开网页" description="保存可访问页面的正文与获取时间，作为可追溯的研究来源。" onClose={()=>setModal(null)}><form onSubmit={importUrl}><Field label="公开网页链接"><input autoFocus required type="url" placeholder="https://example.com/pricing" value={sourceDraft.url} onChange={e=>setSourceDraft({...sourceDraft,url:e.target.value})}/></Field><Field label="资料归属"><select value={sourceDraft.competitor} onChange={e=>setSourceDraft({...sourceDraft,competitor:e.target.value})}><option value="">行业与背景</option>{project?.competitors.map(c=><option key={c}>{c}</option>)}</select></Field><div className="outline-note"><Globe2 size={17}/><p>适用于无需登录的公开页面。若页面无法获取正文，可改为手动添加原文。每个研究工作区最多保存 20 个网页来源。</p></div><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>取消</Button><Button variant="primary" disabled={!!busy}>{busy==='url'?<Loader2 className="spin" size={15}/>:<ArrowDownToLine size={15}/>}获取并保存正文</Button></div></form></Modal>}
  {modal==='revise'&&report&&<Modal error={error} title="让研究再深入一步" description={`基于报告版本 ${report.version} 补充研究，原版本仍会保留。`} onClose={()=>setModal(null)}><form onSubmit={revise}><Field label="你的追问或修改要求"><textarea autoFocus required minLength={3} maxLength={6000} rows={6} placeholder="例如：请进一步核对企业版的 SSO 支持条件，并把报告重点放在中小企业的采购成本。" value={revision} onChange={e=>setRevision(e.target.value)}/></Field><div className="outline-note"><GitBranch size={18}/><p>沿用原报告的{report.mode==='replay'?'固定响应回放':'真实模型'}方式，重新核查相关结论并生成新版本。</p></div><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>取消</Button><Button variant="primary" disabled={!!busy||active}><ArrowRight size={16}/>开始补充研究</Button></div></form></Modal>}
  {inspect&&<div className="drawer-shade" onClick={()=>setInspect(null)}><aside className="evidence-drawer" role="dialog" aria-modal="true" aria-label="证据详情" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><div><span className="eyebrow">EVIDENCE, IN CONTEXT</span><h2>{inspect.source?'资料原文':'结论与证据'}</h2></div><button className="icon-button" aria-label="关闭证据详情" onClick={()=>setInspect(null)}><X size={21}/></button></div><div className="drawer-body">{inspect.source?<><div className="drawer-source-title"><span className="file-icon"><FileText size={23}/></span><h3>{inspect.source.title}</h3></div><div className="pill-row"><Badge tone={inspect.source.synthetic?'amber':'green'}>{inspect.source.synthetic?'虚构测试资料':'真实资料'}</Badge><Badge>版本 {inspect.source.version}</Badge>{sourceHistory.length>1&&<select className="source-version-select" aria-label="查看资料历史版本" value={inspect.source.id} onChange={e=>setInspect({source:sourceHistory.find(s=>s.id===e.target.value)})}>{sourceHistory.map(s=><option key={s.id} value={s.id}>版本 {s.version}{s.active?' · 当前':' · 历史'}</option>)}</select>}<Badge>{inspect.source.competitor||'行业与背景'}</Badge></div><dl className="source-metadata"><div><dt>发布日期</dt><dd>{day(inspect.source.published_at)}</dd></div><div><dt>获取时间</dt><dd>{date(inspect.source.retrieved_at)}</dd></div>{inspect.source.url&&<div><dt>来源链接</dt><dd><a href={safeSourceUrl(inspect.source.url)} target="_blank" rel="noreferrer">访问原始页面<ExternalLink size={13}/></a></dd></div>}</dl>{inspect.quote&&<div className="quote-notice"><Link2 size={15}/>以下高亮为该结论引用的原文片段</div>}<SourceText text={inspect.source.text} quote={inspect.quote??''}/>{!active&&<Button className="full-width" onClick={()=>openSourceForm(inspect.source)}><RefreshCw size={15}/>更新这份资料</Button>}</>:inspect.claims?.length?inspect.claims.map(claim=><div className="claim-card" key={claim.id}><div className="claim-card-top"><span>{claim.subject} · {claim.dimension}</span><Badge tone={claim.status==='supported'?'green':claim.status==='contradicted'?'red':'amber'}>{statusLabel(claim.status)}</Badge></div><h3>{claim.statement}</h3>{claim.conditions.length>0&&<p className="claim-conditions">适用条件：{claim.conditions.join('；')}</p>}{claim.evidence.length?claim.evidence.map((evidence,i)=><button className="quote-card" key={i} onClick={()=>showEvidence(evidence)}><blockquote>“{evidence.quote}”</blockquote><span><FileText size={13}/>{report?.sources.find(s=>s.id===evidence.source_id)?.title??'查看来源'}<ArrowUpRight size={13}/></span>{evidence.locator&&<small>{evidence.locator}</small>}</button>):<p className="muted">当前没有可定位的引用，结论需要进一步确认。</p>}{claim.computation&&<details><summary>计算依据</summary><pre>{JSON.stringify(claim.computation,null,2)}</pre></details>}</div>):<Empty icon={Search} title="尚无可查看的结论" body="该部分暂未关联结论或来源。"/>}</div></aside></div>}
 </div>
}
function Stat({label,value,unit,icon:Icon,note}:{label:string;value:string|number;unit?:string;icon:typeof FolderOpen;note:string}){return <div className="stat-card"><div><span>{label}</span><Icon size={18}/></div><strong>{value}<small>{unit}</small></strong><p>{note}</p></div>}
function PreparationStep({number,title,body,complete}:{number:string;title:string;body:string;complete:boolean}){return <div className={`preparation-step ${complete?'complete':''}`}><span>{complete?<Check size={16}/>:number}</span><div><h4>{title}</h4><p>{body}</p></div></div>}
function SourceText({text,quote}:{text:string;quote:string}){const parts=quoteParts(text,quote);const ref=useRef<HTMLElement>(null);useEffect(()=>{if(parts.match)ref.current?.scrollIntoView({block:'center',behavior:'smooth'})},[parts.match]);return <div className="source-full-text">{parts.before}{parts.match&&<mark ref={ref}>{parts.match}</mark>}{parts.after}</div>}
