import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const base=process.env.BRIEFFORGE_URL??'http://127.0.0.1:8788';
const output=fileURLToPath(new URL('../../artifacts/frontend',import.meta.url));await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
const results=[];const step=async(name,fn)=>{await fn();results.push({name,status:'passed'});console.log(`PASS ${name}`)};
try{
 await page.goto(base);await page.getByRole('button',{name:'创建研究项目'}).waitFor();
 await step('keyboard typing retains focus and create public workspace',async()=>{await page.getByRole('button',{name:'创建研究项目'}).click();const title=page.getByRole('textbox',{name:'项目名称'});await title.click();await title.pressSequentially('Keyboard focus test');assert.equal(await title.inputValue(),'Keyboard focus test');await title.fill(`浏览器交互验收 ${Date.now()}`);await page.getByRole('textbox',{name:'你想研究什么？'}).fill('比较 Alpha 与 Beta 的价格、套餐和 SSO 适用条件。');await page.getByRole('textbox',{name:'比较对象'}).fill('Alpha，Beta');await page.getByRole('button',{name:'保存研究简报'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('heading',{name:'研究概览',exact:true}).waitFor()});
 await step('add source and preserve version history',async()=>{await page.getByRole('button',{name:'资料与证据'}).click();await page.getByRole('button',{name:'添加原文'}).click();await page.getByRole('textbox',{name:'资料标题'}).fill('Alpha 官方价格条款');await page.getByRole('combobox',{name:'资料归属'}).selectOption('Alpha');await page.getByRole('textbox',{name:'资料原文'}).fill('团队版：USD 12/席位/月，按年付费。企业版支持 SSO，需单独询价。');await page.getByRole('button',{name:'添加到资料库'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.source-card').filter({hasText:'Alpha 官方价格条款'}).click();await page.getByRole('button',{name:'更新这份资料'}).click();await page.getByRole('textbox',{name:'资料原文'}).fill('团队版：USD 15/席位/月，按年付费。企业版支持 SSO，需单独询价。');await page.getByRole('button',{name:'保存为新版本'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.source-card').filter({hasText:'Alpha 官方价格条款'}).click();const versions=page.getByRole('combobox',{name:'查看资料历史版本'});await versions.waitFor();assert.equal(await versions.locator('option').count(),2);assert((await page.locator('.source-full-text').textContent()).includes('USD 15'));await versions.selectOption({label:'版本 1 · 历史'});assert((await page.locator('.source-full-text').textContent()).includes('USD 12'));await page.screenshot({path:path.join(output,'09-source-history.png')});await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'})});
 await step('actual file upload',async()=>{await page.locator('input[type=file]').setInputFiles({name:'beta-notes.txt',mimeType:'text/plain',buffer:Buffer.from('Beta 产品说明：仅企业套餐支持 SSO。来源类型：厂商说明。','utf8')});await page.locator('.source-card').filter({hasText:'beta-notes'}).waitFor();assert.equal(await page.locator('.source-card').count(),2)});
 await step('public webpage import UI exists',async()=>{await page.getByRole('button',{name:'导入网页'}).click();await page.getByRole('dialog',{name:'导入公开网页'}).waitFor();assert(await page.getByRole('textbox',{name:'公开网页链接'}).isVisible());await page.getByRole('button',{name:'取消',exact:true}).click()});
 await step('stable mobile snapshots after responsive sidebar closes',async()=>{const projects=await (await page.request.get(`${base}/api/projects`)).json();const project=projects.find(p=>p.latest_report_id);assert(project);await page.getByRole('combobox',{name:'选择研究项目'}).selectOption(project.id);await page.locator('.report-document').waitFor();await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);await page.screenshot({path:path.join(output,'07-mobile-report.png'),fullPage:true});await page.screenshot({path:path.join(output,'10-mobile-report-viewport.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'打开菜单'}).click();await page.getByRole('button',{name:'资料与证据'}).click();await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);await page.screenshot({path:path.join(output,'08-mobile-sources.png'),fullPage:true});await page.screenshot({path:path.join(output,'11-mobile-sources-viewport.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
 assert.deepEqual(errors,[]);results.push({name:'no browser runtime errors',status:'passed'});
}catch(error){console.error(error);process.exitCode=1;results.push({name:'failure',status:'failed',error:String(error)});await page.screenshot({path:path.join(output,'interaction-failure.png'),fullPage:true})}finally{await writeFile(path.join(output,'interaction-results.json'),JSON.stringify(results,null,2));await browser.close()}
