import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';

const base=process.env.BRIEFFORGE_URL??'http://127.0.0.1:8788';
const output=path.resolve(fileURLToPath(new URL('../../artifacts/frontend',import.meta.url)));
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1,recordVideo:{dir:path.join(output,'recording'),size:{width:1440,height:1100}}});
const projects=await (await context.request.get(`${base}/api/projects`)).json();
const existing=projects.find(p=>p.latest_report_id);
if(existing)await context.addInitScript(id=>{if(!localStorage.getItem('briefforge.project'))localStorage.setItem('briefforge.project',id)},existing.id);
const page=await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const results=[];
const step=async(name,fn)=>{await fn();results.push({name,status:'passed'});console.log(`PASS ${name}`)};
try{
 await step('load persisted workspace',async()=>{await page.goto(base);await page.getByRole('navigation',{name:'工作台导航'}).waitFor();await page.locator('.page-heading, .welcome').waitFor();await page.screenshot({path:path.join(output,'01-report-desktop.png'),fullPage:true})});
 await step('new synthetic demo and source inspection',async()=>{await page.getByRole('button',{name:'体验内置案例'}).click();await page.getByRole('heading',{name:'研究概览',exact:true}).waitFor();await page.getByRole('button',{name:'资料与证据'}).click();await page.locator('.source-card').first().waitFor();assert.equal(await page.locator('.source-card').count(),30);await page.locator('.source-card').first().click();await page.getByRole('dialog',{name:'证据详情'}).waitFor();assert((await page.locator('.source-full-text').textContent()).length>20);await page.getByRole('button',{name:'关闭证据详情'}).click();await page.screenshot({path:path.join(output,'02-sources-desktop.png'),fullPage:true})});
 await step('brief editing persists',async()=>{await page.getByRole('button',{name:'研究概览',exact:true}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('textbox',{name:'报告面向谁'}).fill('管理层与产品团队 · 浏览器验收');await page.getByRole('button',{name:'保存研究简报'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByText('管理层与产品团队 · 浏览器验收').first().waitFor()});
 await step('confirm outline and execute replay',async()=>{await page.getByRole('button',{name:'确认研究大纲',exact:true}).click();await page.getByRole('dialog',{name:'确认研究大纲'}).waitFor();await page.getByRole('button',{name:'确认并开始研究'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('heading',{name:'报告与导出',exact:true}).waitFor({timeout:120000});await page.locator('.report-document').waitFor();assert((await page.locator('.report-document').textContent()).includes('固定响应回放'));await page.screenshot({path:path.join(output,'03-completed-replay.png'),fullPage:true})});
 await step('claim evidence links to exact frozen quote',async()=>{await page.locator('.evidence-link').first().click();await page.locator('.quote-card').first().waitFor();const quote=await page.locator('.quote-card blockquote').first().textContent();await page.locator('.quote-card').first().click();await page.locator('.source-full-text mark').waitFor();assert.equal(await page.locator('.source-full-text mark').textContent(),quote.slice(1,-1));await page.screenshot({path:path.join(output,'04-evidence-drawer.png')});await page.getByRole('button',{name:'关闭证据详情'}).click()});
 await step('durable collaboration history',async()=>{await page.getByRole('button',{name:'协作进度',exact:true}).click();await page.locator('.task-card').first().waitFor();assert((await page.locator('.task-card').count())>6);assert((await page.locator('.event-item').count())>6);await page.screenshot({path:path.join(output,'05-collaboration.png'),fullPage:true});await page.reload();await page.getByRole('button',{name:'协作进度',exact:true}).click();await page.locator('.task-card').first().waitFor()});
 await step('revision creates immutable new version',async()=>{await page.getByRole('button',{name:'报告与导出',exact:true}).click();await page.getByRole('button',{name:'追问与修改'}).click();await page.getByRole('textbox',{name:'你的追问或修改要求'}).fill('请再次核对企业版 SSO 的适用条件，并保留尚无法确认的信息。');await page.getByRole('button',{name:'开始补充研究'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('heading',{name:'报告与导出',exact:true}).waitFor({timeout:120000});assert.equal(await page.getByRole('combobox',{name:'选择报告版本'}).locator('option').count(),2)});
 await step('word and pptx exports reach downloadable state',async()=>{await page.getByRole('button',{name:'导出 Word'}).click();await page.locator('.export-notice').filter({hasText:'DOCX'}).getByRole('link',{name:'下载文件'}).waitFor({timeout:120000});const word=page.locator('.export-notice').filter({hasText:'DOCX'}).getByRole('link',{name:'下载文件'});const wordHref=await word.getAttribute('href');const response=await context.request.get(`${base}${wordHref}`);assert.equal(response.status(),200);assert((await response.body()).byteLength>1000);await page.getByRole('button',{name:'导出 PPT'}).click();await page.locator('.export-notice').filter({hasText:'PPTX'}).getByRole('link',{name:'下载文件'}).waitFor({timeout:120000});const pptHref=await page.locator('.export-notice').filter({hasText:'PPTX'}).getByRole('link',{name:'下载文件'}).getAttribute('href');assert.equal((await context.request.get(`${base}${pptHref}`)).status(),200);await page.screenshot({path:path.join(output,'06-export-ready.png')})});
 await step('responsive mobile without page overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);await page.screenshot({path:path.join(output,'07-mobile-report.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.getByRole('button',{name:'打开菜单'}).click();await page.getByRole('button',{name:'资料与证据'}).click();await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);await page.screenshot({path:path.join(output,'08-mobile-sources.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1))});
 assert.deepEqual(errors,[]);
 results.push({name:'browser runtime errors',status:'passed',errors});
}catch(error){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});results.push({name:'failure',status:'failed',error:String(error),browserErrors:errors});console.error(error);process.exitCode=1}
finally{await writeFile(path.join(output,'e2e-results.json'),JSON.stringify(results,null,2));await context.close();await browser.close()}
